Add thanos resources
CarnegieMellon-PlantD/PlantD-operator pull request #34
Opened 2024-03-08 06:33 UTC by ankushbbbr

2024-03-08 15:53 UTC, baljit92 requested changes

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +	thanosVersion := "v0.34.0"
Can we move these to config.go?

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +					TargetPort: intstr.FromInt(9090),
Move them to _config.go_

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +				"app": "thanos-querier",
Move them to _config.go_

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +					Protocol:   corev1.ProtocolTCP,
Move them to config.go

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +				"prometheus": "prometheus",
Move to config.go

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +								},
Move them to config.go

2024-03-08 15:53 UTC, baljit92 commented on pkg/core/core.go
> +				Key: "thanos.yaml",
Can we move this to config.go?

2024-03-08 16:37 UTC, tomzhu1024 commented on pkg/core/core.go
> -
Is this intentional, or a mistake?

2024-03-09 00:50 UTC, ankushbbbr commented
Moved configurable parameters to config.yaml

2024-03-12 20:38 UTC, tomzhu1024 approved these changes

2024-03-12 20:41 UTC, merged