fix: cannot get k6 testrun
CarnegieMellon-PlantD/PlantD-operator pull request #5
Opened 2023-09-15 17:41 UTC by tomzhu1024

2023-09-15 20:59 UTC, zitengshu requested changes
Requested a change.

2023-09-15 20:59 UTC, zitengshu commented on pkg/loadgen/loadgen.go
`name`-`endpointName` is the testRun name.

2023-09-15 20:59 UTC, zitengshu commented on pkg/loadgen/loadgen.go
Please call `GetTestRunName` here, instead passing testRunName through the function parameter.

2023-09-16 06:39 UTC, tomzhu1024 commented on pkg/loadgen/loadgen.go
`GetTestRunName` is a function in `internal/controller/experiment_controller.go`. I assume it's not the best practice to use this function inside `pkg/loadgen/loadgen.go`, because everything in `pkg` should be the callee. Maybe I should move the function or keep the current signature changes?

2023-09-16 06:39 UTC, tomzhu1024 commented on pkg/loadgen/loadgen.go
Fixed.

2023-09-16 22:00 UTC, zitengshu approved these changes
LGTM

2023-09-16 22:00 UTC, merged